name: Build and cache dependencies

on:
  pull_request:
    paths:
      - vcpkg**.json
      - .github/workflows/dependency-cache.yaml
  workflow_dispatch:

jobs:
  cache:

    env:
      NUGET_SOURCE_NAME: github

    name: ${{ matrix.os }} - ${{ matrix.cmake_preset }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-12 ]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Authenticate to GitHub NuGet registry
      run: |
        mono `vcpkg fetch nuget | tail -n 1` \
        sources add \
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
        -storepasswordincleartext \
        -name "${{ env.NUGET_SOURCE_NAME }}" \
        -username "${{ github.actor }}" \
        -password "${{ secrets.GITHUB_TOKEN }}"
        mono `vcpkg fetch nuget | tail -n 1` \
        setapikey "${{ secrets.GITHUB_TOKEN }}" \
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: Do vcpkg work
      env:
        VCPKG_BINARY_SOURCES: 'clear;nuget,${{ env.NUGET_SOURCE_NAME }},readwrite'
      run: vcpkg install

